apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    dev.okteto.com/generate-host: "true"
spec:
#  tls:
#    - hosts:
#      - api.acuderman.cloud.okteto.net
#      secretName: secret/ssl
  rules:
    - host: "api.acuderman.cloud.okteto.net"
      http:
        paths:
          - path: /
#            pathType: Prefix
            backend:
              serviceName: fconnect-cluster-ip-service
              servicePort: 3000
